name: reddit_clone
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.1
  firebase_storage: ^11.0.3
  cloud_firestore: ^4.0.3
  firebase_auth: ^4.1.0
  google_sign_in: ^5.4.2
  flutter_riverpod: ^2.0.2
  fpdart: ^0.3.0
  routemaster: ^1.0.1
  dotted_border: ^2.0.0+3
  file_picker: ^5.2.2
  shared_preferences: ^2.0.15
  uuid: ^3.0.6
  any_link_preview: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf